# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ecacff701f2393085c074a0fd42c6d514f893bd685022734b9e596042851fc8effd8afd1dd756a57941452ddef05a3e58250bff27f7445ad0355743db13b36

test:
  secret_key_base: 14045cbfcd552ec936865188d9851e92faf0d7814c39ba19732b896f4b340edabcc2b32ad91531b6be809231cb00007d1e5459b679f38d275f58ea0d9c1201ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
